# Generated by Django 5.2.7 on 2026-04-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookroom", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room",
            new_name="room_number",
        ),
    ]
